Sell-it.Web/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sell_it.Data;
using Sell_it.Data.Entities;
using Sell_it.Service.CategoryServices;

namespace Sell_it.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private const string EXISTING_CATEGORY_ERROR_MESSAGE = "A Category with that Name already exists!";

        private readonly SellItContext context;
        private readonly ICategoryService categoryService;

        public CategoriesController(SellItContext context,
                                    ICategoryService categoryService)
        {
            this.context = context;
            this.categoryService = categoryService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(categoryService.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            bool doesCategoryExist = categoryService.GetAll()
                                .Where(c => c.Name.ToLower().Equals(category.Name.ToLower()))
                                .Any();

            if (doesCategoryExist)
            {
                ViewBag.ErrorMessage = EXISTING_CATEGORY_ERROR_MESSAGE;
                return View();
            }

            categoryService.Create(category);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            Category category = categoryService.Get(id);

            if (category == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            bool doesCategoryExist = categoryService.GetAll()
                                .Where(c => c.Name.ToLower().Equals(category.Name.ToLower()))
                                .Any();

            if (doesCategoryExist)
            {
                ViewBag.ErrorMessage = EXISTING_CATEGORY_ERROR_MESSAGE;
                return View(category);
            }

            categoryService.Update(category);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            Category category = categoryService.Get(id);

            if (category == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        [HttpPost]
        public IActionResult Delete(Category category)
        {
            categoryService.Delete(category);
            return RedirectToAction(nameof(Index));
        }
    }
}

Sell-it.Web/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sell_it.Data;
using Sell_it.Data.Entities;
using Sell_it.Service.CategoryServices;
using Sell_it.Service.PhotoServices;
using Sell_it.Service.ProductServices;
using Sell_it.Web.Models;

namespace Sell_it.Web.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly SellItContext context;
        private readonly UserManager<User> userManager;

        private readonly IProductService productService;
        private readonly IPhotoService photoService;
        private readonly ICategoryService categoryService;

        public ProductsController(SellItContext context, 
                                  IProductService productService,
                                  IPhotoService photoService,
                                  ICategoryService categoryService,
                                  UserManager<User> userManager)
        {
            this.context = context;
            this.productService = productService;
            this.photoService = photoService;
            this.categoryService = categoryService;
            this.userManager = userManager;
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            ViewData["CategoryId"] = new SelectList(categoryService.GetAll(), "Id", "Name");
            ProductListViewModel model = new ProductListViewModel();
            model.Products = productService.GetAll();
            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Index(ProductListViewModel model)
        {
            ProductListViewModel filteredViewModel = FilterViewModel(model);

            ViewData["CategoryId"] = new SelectList(categoryService.GetAll(), "Id", "Name");
            return View(filteredViewModel);
        }

        [HttpGet]
        public IActionResult MyProducts()
        {
            string userId = userManager.GetUserId(User);

            ProductListViewModel model = new ProductListViewModel();
            model.Products = productService.GetAll().Where(p => p.Seller.Id.Equals(userId)).ToList();

            ViewData["CategoryId"] = new SelectList(categoryService.GetAll(), "Id", "Name");
            return View(model);
        }

        [HttpPost]
        public IActionResult MyProducts(ProductListViewModel model)
        {
            string userId = userManager.GetUserId(User);

            ProductListViewModel filteredViewModel = FilterViewModel(model);
            filteredViewModel.Products = filteredViewModel.Products.Where(p => p.Seller.Id.Equals(userId)).ToList();
            
            ViewData["CategoryId"] = new SelectList(categoryService.GetAll(), "Id", "Name");
            return View(filteredViewModel);
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Details(Guid id)
        {
            Product product = productService.Get(id);
            if (product == null)
            {
                return RedirectToAction(nameof(Index));
            }

            product.Photos = photoService.GetProductPhotos(product.Id);
            product.Category = categoryService.GetProductCategory(product.CategoryId);

            return View(product);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(categoryService.GetAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(IFormCollection collection, ProductCreateViewModel model)
        {
            Product product = new Product();

            product.Name = model.Name;
            product.Description = model.Description;

            product.Price = GetParsedProductPrice(collection);

            product.UserId = userManager.GetUserId(User);

            var categoryId = collection["CategoryId"];
            product.Category = categoryService.GetProductCategory(Guid.Parse(categoryId));

            foreach (string imgUrl in model.ImageUrls)
            {
                Photo productPhoto = new Photo()
                {
                    Id = new Guid(),
                    ProductId = product.Id,
                    Path = imgUrl
                };

                product.Photos.Add(productPhoto);
            }

            productService.Create(product);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            Product product = productService.Get(id);
            
            if (product == null || product.UserId != userManager.GetUserId(User))
            {
                return RedirectToAction(nameof(Index));
            }

            ViewData["CategoryId"] = new SelectList(categoryService.GetAll(), "Id", "Name");

            ProductCreateViewModel model = new ProductCreateViewModel
            {
                Id = id,
                Name = product.Name,
                Description = product.Description,
                Price = product.Price,
                CategoryId = product.CategoryId
            };

            product.Photos = photoService.GetProductPhotos(product.Id);
            
            foreach(Photo photo in product.Photos)
            {
                model.ImageUrls.Add(photo.Path);
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(IFormCollection collection, ProductCreateViewModel model)
        {
            Product product = new Product
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description
            };

            product.Photos = photoService.GetProductPhotos(product.Id);

            photoService.UpdateProductPhotos(product, model.ImageUrls);

            product.UserId = userManager.GetUserId(User);

            var categoryId = collection["CategoryId"];
            product.Category = categoryService.GetProductCategory(Guid.Parse(categoryId));

            product.Price = GetParsedProductPrice(collection);

            productService.Update(product);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            Product product = productService.Get(id);

            if (product == null || product.UserId != userManager.GetUserId(User))
            {
                return RedirectToAction(nameof(Index));
            }

            product.Photos = photoService.GetProductPhotos(product.Id);
            product.Category = categoryService.GetProductCategory(product.CategoryId);

            return View(product);
        }

        [HttpPost]
        public IActionResult Delete(Product product)
        {
            productService.Delete(product);
            return RedirectToAction(nameof(Index));
        }

        private static decimal GetParsedProductPrice(IFormCollection collection)
        {
            string stringPrice = collection["Price"].ToString().Replace('.', ',');
            decimal productPrice = decimal.Parse(stringPrice);
            return productPrice;
        }

        private ProductListViewModel FilterViewModel(ProductListViewModel model)
        {
            List<Product> filtered = new List<Product>();

            switch (model.PriceOrder)
            {
                case "Ascending":
                    filtered = productService.Filter(model.CategoryId, model.SearchName);
                    break;
                case "Descending":
                    filtered = productService.FilterDesc(model.CategoryId, model.SearchName);
                    break;
            }

            ProductListViewModel filteredViewModel = new ProductListViewModel()
            {
                Products = filtered,
                CategoryId = model.CategoryId
            };
            return filteredViewModel;
        }
    }
}

Sell-it.Web/Controllers/PurchasesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Sell_it.Data;
using Sell_it.Data.Entities;
using Sell_it.Service.CategoryServices;
using Sell_it.Service.PhotoServices;
using Sell_it.Service.ProductServices;
using Sell_it.Service.PurchaseServices;
using Sell_it.Service.UserServices;

namespace Sell_it.Web.Controllers
{
    [Authorize]
    public class PurchasesController : Controller
    {
        private readonly SellItContext context;
        private readonly UserManager<User> userManager;

        private readonly IPurchaseService purchaseService;
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;
        private readonly IPhotoService photoService;
        private readonly IUserService userService;

        public PurchasesController(SellItContext context,
                                   IPurchaseService purchaseService,
                                   IProductService productService,
                                   ICategoryService categoryService,
                                   IPhotoService photoService,
                                   IUserService userService,
                                   UserManager<User> userManager)
        {
            this.context = context;
            this.purchaseService = purchaseService;
            this.productService = productService;
            this.categoryService = categoryService;
            this.photoService = photoService;
            this.userService = userService;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Buy(Guid productId)
        {
            Product product = productService.Get(productId);
            string userId = userManager.GetUserId(User);

            if (product == null || userId == product.UserId)
            {
                return RedirectToAction("Index", "Products");
            }

            Purchase purchase = new Purchase();

            product.Seller = userService.Get(product.UserId);
            product.Category = categoryService.GetProductCategory(product.CategoryId);
            product.Photos = photoService.GetProductPhotos(productId);

            purchase.Buyer = userService.Get(userId);
            purchase.Product = product;

            return View(purchase);
        }

        [HttpPost]
        public IActionResult Buy(Purchase purchase)
        {
            Product product = productService.Get(purchase.ProductId);

            product.Seller = userService.Get(product.UserId);
            product.Category = categoryService.GetProductCategory(product.CategoryId);

            purchase.Product = product;
            purchase.Buyer = userService.Get(userManager.GetUserId(User));

            purchaseService.Create(purchase);

            return RedirectToAction(nameof(MyPurchases));
        }

        [HttpGet]
        public IActionResult MyPurchases()
        {
            List<Purchase> purchases = purchaseService.GetAll()
                            .Where(p => p.BuyerId.Equals(userManager.GetUserId(User)))
                            .ToList();

            purchases.ForEach(p => {
                p.Product.Seller = userService.Get(p.Product.UserId);
                p.Product.Category = categoryService.Get(p.Product.CategoryId);
                p.Product.Photos = photoService.GetProductPhotos(p.ProductId);
                });

            return View(purchases);
        }

        [HttpGet]
        public IActionResult Remove(Guid id)
        {
            Purchase purchase = purchaseService.Get(id);
            purchaseService.Delete(purchase);
            return RedirectToAction(nameof(MyPurchases));
        }
    }
}

Sell-it.Web/Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Sell_it.Data;
using Sell_it.Data.Entities;
using Sell_it.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Sell_it.Service.UserServices;

namespace Sell_it.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly SellItContext context;
        private readonly UserManager<User> userManager;

        private readonly IUserService userService;

        public RolesController(SellItContext context,
                               IUserService userService,
                               UserManager<User> userManager)
        {
            this.context = context;
            this.userService = userService;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<UserRolesViewModel> userRoles = new List<UserRolesViewModel>();

            userRoles = context.Users.Select(u => new UserRolesViewModel
            {
                UserId = u.Id,
                UserName = u.UserName,
                Role = userManager.GetRolesAsync(u).Result.ToList()[0]
            }).ToList();

            return View(userRoles);
        }

        [HttpGet]
        public IActionResult Manage(string userId)
        {
            User user = userService.Get(userId);

            if (user == null)
            {
                return RedirectToAction(nameof(Index));
            }

            UserRolesViewModel model = new UserRolesViewModel
            {
                UserId = user.Id,
                UserName = user.UserName,
                Role = userManager.GetRolesAsync(user).Result.ToList()[0]
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Manage(UserRolesViewModel model)
        {
            User user = userService.Get(model.UserId);

            if (user == null)
            {
                RedirectToAction(nameof(Index));
            }

            var userRoles = await userManager.GetRolesAsync(user);
            await userManager.RemoveFromRolesAsync(user, userRoles);

            await userManager.AddToRoleAsync(user, model.Role);

            return RedirectToAction(nameof(Index));
        }
    }
}

Sell-it.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Sell_it.Data.Entities
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sell.it</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sell_it.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sell.it</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">All Products</a>
                        </li>
                        @if(User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Create">Create Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="MyProducts">My Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Purchases" asp-action="MyPurchases">My Purchases</a>
                            </li>
                        }
                        @if(User.IsInRole(Roles.Admin.ToString()))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Admin Panel
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Manage Users' Roles</a>
                                    <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Manage Categories</a>
                                    <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Create">Create Category</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Sell_it.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>